--- #YAML:1.0
name:                WWW-CPAN
version:             0.001
abstract:            ~
license:             perl
author:              
    - Adriano R. Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.38
distribution_type:   module
requires:     
    Class::Accessor:               0
    JSON::Any:                     0
    LWP::UserAgent:                0
    parent:                        0
    strict:                        0
    Test::More:                    0
    warnings:                      0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
